name: Build Tweak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Ensure main utils are installed
        uses: dhinakg/procursus-action@main
        with:
          packages: coreutils make xz ldid
      - name: Checkout Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Checkout iOS SDK
        uses: actions/checkout@v4
        with:
          repository: theos/sdks
          path: theos/sdks
          sparse-checkout: iPhoneOS16.5.sdk
          sparse-checkout-cone-mode: false
      - name: Build Package
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make STRIP=0
          zip -r ./packages.zip ./packages
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MixEverywhere
          path: ./packages.zip
