name: Build Tweak

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential ldid xz-utils
      - name: Checkout Theos
        uses: actions/checkout@v4
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Checkout iOS SDK
        uses: actions/checkout@v4
        with:
          repository: theos/sdks
          path: theos/sdks
          sparse-checkout: iPhoneOS16.5.sdk
          sparse-checkout-cone-mode: false
      - name: Build Package
        run: |
          export THEOS=$GITHUB_WORKSPACE/theos
          make package FINALPACKAGE=1 STRIP=0
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MixEverywhere-deb
          path: ./packages/*.deb
